### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#16]
Hi all,

apologies for the long silence, but this is an attempt to revive this manuscript and get it to a publishable state for the next issue of livecoms. I will identify tasks in the next days and would be happy to assign them to willing volunteers (Including myself). Are people ok with this idea? @andrrizzi, @jchodera, @davidlmobley, @Lnaden, @mrshirts, @brycestx  

Also would everyone be interested in a virtual chat in the next week or two or so? I'd be happy to arrange this. However, I am also fine to just work with github (or emails if this is preferred), but it seemed easier to get everyone who contributed to this so far tagged. Any thoughts? 

If you want to invite anyone else to work on this please go ahead. 

Best,
-Toni

**Comment by jchodera** [comment]
I'm in! I arrive in NYC and am available to do lots of writing through Feb. 
@andrrizzi is in Italy now and may be easier to coordinate in your time zone.

**Comment by ppxasjsm** [comment]
Thanks @jmichel80, @brycestx and @jchodera  sounds great!

**Comment by davidlmobley** [comment]
I'm happy to contribute some and will certainly have time to edit. I won't have time to do lots of combing the literature but I can probably generate some significant blocks of text if you give me well-defined things you want written (I write and edit fast; it's the other parts which are slow).
