### ISSUE TITLE
Virtual meetup

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#19]
Hi all,
apologies for Spamming. Trying to get the polling feature to work. 
it would be great to get some people together for a virtual meetup. I would propose the following two dates and if at least 3+ people can join we can go ahead with a virtual discussion and share the outcome with the rest.

I'll pick the option with most people available, currently by default I can make all of the suggested times:

Wednesday, January 30th options:
[![](https://api.gh-polls.com/poll/01D2AS6NAFN3KP3V3PV0YKF980/11%3A30am%20EST)](https://api.gh-polls.com/poll/01D2AS6NAFN3KP3V3PV0YKF980/11%3A30am%20EST/vote)
[![](https://api.gh-polls.com/poll/01D2AS6NAFN3KP3V3PV0YKF980/3%3A00%20pm%20EST)](https://api.gh-polls.com/poll/01D2AS6NAFN3KP3V3PV0YKF980/3%3A00%20pm%20EST/vote)
[![](https://api.gh-polls.com/poll/01D2AS6NAFN3KP3V3PV0YKF980/4%3A00%20pm%20EST)](https://api.gh-polls.com/poll/01D2AS6NAFN3KP3V3PV0YKF980/4%3A00%20pm%20EST/vote)

Monday, February 4th options:
[![](https://api.gh-polls.com/poll/01D2AS6Q47QRHVFJWN18HXA2FG/11%3A00am%20EST)](https://api.gh-polls.com/poll/01D2AS6Q47QRHVFJWN18HXA2FG/11%3A00am%20EST/vote)
[![](https://api.gh-polls.com/poll/01D2AS6Q47QRHVFJWN18HXA2FG/12%3A00%20pm%20EST)](https://api.gh-polls.com/poll/01D2AS6Q47QRHVFJWN18HXA2FG/12%3A00%20pm%20EST/vote)
[![](https://api.gh-polls.com/poll/01D2AS6Q47QRHVFJWN18HXA2FG/1%3A00%20pm%20EST)](https://api.gh-polls.com/poll/01D2AS6Q47QRHVFJWN18HXA2FG/1%3A00%20pm%20EST/vote)

**Comment by ppxasjsm** [comment]
Topics to I would like to talk about:

- Identify a set of figures to enhance the comprehensibility of the manuscript. @jchodera suggested asking Christopher Fennell to illustrate them if he was interested. 

- Identify clear heading sections to be easily assigned for people to write sections. 

- Draft project board to make it easier to keep track of progress, this is primarily for myself, but I would like some input on this if possible.

**Comment by samarjeet** [comment]
Hi, 
  Are we meeting today at 11:30 EST?

**Comment by ppxasjsm** [comment]
Hi,

I set up a meeting for next Monday, since it was easier for me than today.

I’ll send you an invite, must have missed you off the invite list. Apologies.

Toni
--
Dr Antonia Mey
University of Edinburgh
Department of Chemistry
Joseph Black Building
Edinburgh
EH9 3FJ

Tel: +44 1316507748
________________________________
