### ISSUE TITLE
8.3 Typical ways of examining output ways and useful plot

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#21]
Examining output data for common problems with discussions of what exactly to plot or look at; examples of typical curves for dV/dlambda and free energy versus lambda, etc.

**Comment by ppxasjsm** [comment]
I am preparing some plots for this and am happy to contribute here.

**Comment by brycestx** [comment]
@ppxasjsm I added a figure looking at differences in forward and reverse free energy estimation using different fractions of the simulation.

**Comment by ppxasjsm** [comment]
Figure looks great! Thanks.
