### ISSUE TITLE
8.4 Estimators for free energies

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#22]
TI, MBAR, BAR, other estimators?

**Comment by ppxasjsm** [comment]
@mrshirts, if you could focus on this section that would be great! It's in section 4 (step 3) number 4 of the current version of the manuscirpt.

**Comment by mrshirts** [comment]
I think that this has been addressed, and maybe subsumed by other sections now?

**Comment by ppxasjsm** [comment]
Yes it has. I'll close this issue. Thank you!
