### ISSUE TITLE
8.5 Uncertain estimation

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#23]
What are good strategies to report uncertainties on DG and DDG?

**Comment by brycestx** [comment]
Great, almost finished writing and compiling references for this section. I will update when finished and added to overleaf

**Comment by ppxasjsm** [comment]
Hey @brycestx how are you getting on here? I haven't seen an update on overleaf yet. Any can add it?

**Comment by brycestx** [comment]
Hey @ppxasjsm that's interesting, you don't see any edits added at line 840? (I think my username is b.allen10 but I'm not sure how I show up on overleaf). I am still working on adding more substance and examples to the section and will update when I am finished.

**Comment by ppxasjsm** [comment]
Ah sorry, I missed this amongst Michael shirts updates. Do you know when you will be done with your updates?

**Comment by brycestx** [comment]
@ppxasjsm great question. I was hoping to have it done last weekend, but alas it is already midweek. I will have it done by Friday morning.

**Comment by brycestx** [comment]
@ppxasjsm Done with my updates for now.

**Comment by ppxasjsm** [comment]
Thank you!
