### ISSUE TITLE
Section 5 What can be expected from alchemical simulations

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#25]
@davidlmobley I think it would be great if Huafeng could write part of this section. I will email him separately, but just putting it here so that I remember.

**Comment by davidlmobley** [comment]
Took a pass at this in Overleaf. I'll also e-mail Huafeng.

**Comment by ppxasjsm** [comment]
Thank you!

**Comment by davidlmobley** [comment]
Is more needed on this @ppxasjsm or are we in OK shape here? LMK if you need me to either nag Huafeng or take another pass.

**Comment by ppxasjsm** [comment]
Will let you know if more is required here.
