### ISSUE TITLE
Section 7.+ Stopping conditions section for simulations

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#33]
What are typical simulation stopping conditions?
Data saving and frequency, what is essential for analysis?

**Comment by Lnaden** [comment]
I've made a pass on this section, as has @brycestx.

**Comment by ppxasjsm** [comment]
Great! Thanks a lot!

**Comment by davidlmobley** [comment]
Should we mark this as closed, @ppxasjsm ?
