### ISSUE TITLE
raw data for figure 7 -- convergence of DG from SAMPL

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#35]
I have been going through figures again. It would be quite useful to get the data for all of the figures, so that  if in doubt it would be possible to redo some of the plots. I may have had this data already, but can't find it now. Who can help?

**Comment by ppxasjsm** [comment]
Talking about this figure:
[free_energy_trajectories.pdf](https://github.com/michellab/alchemical-best-practices/files/3833519/free_energy_trajectories.pdf)

**Comment by mrshirts** [comment]
So, the person who generated this is @andrrizzi IIRC.

**Comment by andrrizzi** [comment]
I still have figures and code I used to generate this. I'll upload both of them in the paper/figures/fig7 directory in the next few days.

**Comment by ppxasjsm** [comment]
Yes please do! Thank you :)
