### ISSUE TITLE
[Figure X] Sampling schemes figure [help]

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#37]
I am trying to converge on some of the figures, before finally sending out a paper draft. 

I have created the following figure to illustrate different sampling schemes for alchemical free energies. Happy to hear some thoughts on it for improvements. 

[sampling_schemes.pdf](https://github.com/michellab/alchemical-best-practices/files/3879081/sampling_schemes.pdf)

**Comment by JenkeScheen** [comment]
- The figure might be clearer divided into distinct panels (square, 2x2)
- Either use the stopwatch icon or 'time'; both is double
- The dashed arrows in B are off. I would suggest using black dashed lines without arrowheads (same for C)
- In D, ns/μs counts for the whole figure, so should be somewhere up top
- Personally I like kde-plot-like distributions better than filling up the AUC 
- The distribution formatting is inconsistent between A, C vs B

- I think in general it might be a good idea to reduce the colouring (doesn't add a lot of information but increases the noise), or at least adopting a colourblind-friendly colourscheme

**Comment by ppxasjsm** [comment]
> * The figure might be clearer divided into distinct panels (square, 2x2)
I agree

> * Either use the stopwatch icon or 'time'; both is double
Good point
> * The dashed arrows in B are off. I would suggest using black dashed lines without arrowheads (same for C)
mmh yeah I know they are off...will work on that bit. There is a difference between the B ones, one is accepted and the other isn't. Colour may not be the best either. 
> * In D, ns/μs counts for the whole figure, so should be somewhere up top
Nope it does not. You run much longer simulations for the non-equilibrium scheme. I should probably give a time estimate for the other ones though. 
> * Personally I like kde-plot-like distributions better than filling up the AUC
The filling up in this case indicates whether the sampling came form a single replica or a mixture, hence having a gradient in the fill. Maybe this doesn't come across as such. 

> * The distribution formatting is inconsistent between A, C vs B
Will change the alpha, good spot. 
> * I think in general it might be a good idea to reduce the colouring (doesn't add a lot of information but increases the noise), or at least adopting a colourblind-friendly colourscheme
Ugh, I though I had..will revise colours.

**Comment by ppxasjsm** [comment]
Updated version:
[sampling_schemes.pdf](https://github.com/michellab/alchemical-best-practices/files/3879409/sampling_schemes.pdf)

**Comment by JenkeScheen** [comment]
great! the boxes do a good job in seperating the methods. Some more nitpicking:
-  all sections have a slight kink in the second distribution  
- section B's distributions are disconnected from the vertical black line
- perhaps it would make sense to remove 'neq MD' from D seeing as all other sections are minimally verbose too. Neq MD would be mentioned in the figure description I would assume

**Comment by ppxasjsm** [comment]
> great! the boxes do a good job in seperating the methods. Some more nitpicking:
> 
> * all sections have a slight kink in the second distribution
But it's a KDE!

> * section B's distributions are disconnected from the vertical black line
> * perhaps it would make sense to remove 'neq MD' from D seeing as all other sections are minimally verbose too. Neq MD would be mentioned in the figure description I would assume

Mmmh dunno. I think D needs more info anyway.

**Comment by davidlmobley** [comment]
On the whole I really like the look of this and I don't have further suggestions. REALLY nice idea to illustrate these this way; people are going to love this figure I think. We'll probably see it everywhere.

**Comment by ppxasjsm** [comment]
Great. I'll leave it in its current state for now.
