### ISSUE TITLE
Pick relative or absolute, weak binders, and restraint bias

### ISSUE THREAD

**Issue by andrrizzi** [michellab/alchemical-best-practices#4]
Might be early for rounds of comments, but I wanted to save these somewhere. I'm not a practitioner of relative free energy calculations so apologies if some of this doesn't make sense, but here are a couple of points that might need to be clarified in the paper.

- **Section 5/Checklist**: Since the paper is targeted towards new practitioners, it might be useful to give a broad overview that **guides choosing the right type of calculation** by highlighting the main differences between relative vs absolute calculations with pros and cons. For example:
  - The quantity of interest (i.e. DeltaG vs DeltaDeltaG).
  - Typical convergence performance on small transformations and transformations that affect the ligand scaffold and/or binding mode.
- **Section 7**: With **weak binders**, do relative free energy calculations require a restraint too? If not, how should people handle them? Also, at least for absolute calculations, should we mention the dependency of the final free energy on the restraint parameters?
- **Section 8**: Should we mention that **restraints can introduce a bias** in the estimated free energy? We've observed this with harmonic restraints. The correction is usually negligible with flat-bottom restraints when they have "steep" walls. I'm not sure about orientational restraints like Boresch.
- **Section 10**: YANK includes setup and analysis tools, although they mostly work only for YANK calculations so I'm not sure we want to include them separately.

**Comment by davidlmobley** [comment]
In general all of that would be great, but some are still research questions, e.g. no one has yet compared efficiency of absolute vs relative calculations that I know of. So I don't know that we can give a guide that's founded on anything other than "conventional wisdom" which, outside our groups, mainly means "always do relative calculations unless you have to do absolute." 

Relative calculations: Probably could require a restraint for weak binders but I am not aware that this has ever been looked at in the literature.

Absolute: Good to mention dependence on restraint. 

Restraint bias: Yes, absolutely.

**Comment by jchodera** [comment]
> Section 8: Should we mention that restraints can introduce a bias in the estimated free energy? We've observed this with harmonic restraints. The correction is usually negligible with flat-bottom restraints when they have "steep" walls. I'm not sure about orientational restraints like Boresch.

I think we can at least illustrate where this arises from: If the restraints are kept on during an absolute calculation, the bound species is explicitly being defined by the restraint. If the restraints are turned on during an absolute calculation, the kinetically accessible region (which may be poorly defined) is used to define the binding site. There are pitfalls with both approaches that we can make explicit.

**Comment by jmichel80** [comment]
> Relative calculations: Probably could require a restraint for weak binders but I am not aware that this has ever been looked at in the literature.
> 
In  J. Mol. Biol., 429(16), 2556-2570 2017 we used flat-bottom distance restraints on fragments to keep them bound to a target pocket. This was deemed necessary because the non-binders tended to unbind otherwise during some windows, clouding the interpretation of the calculated binding energies. We also wanted to compare binding energies for different pockets.

> Absolute: Good to mention dependence on restraint.
> 
> Restraint bias: Yes, absolutely.
> 
Yes this is important to mention. 
We typically start with a rules of thumb to define flat-bottom restraints such that the restraint energies are null when applied to the bound state, but kick in for the decoupled state without allowing a too large volume.

I’m not aware of a systematic study of the effect of restraints in the literature.

**Comment by ppxasjsm** [comment]
@andrrizzi Has this been dealt with?

**Comment by ppxasjsm** [comment]
@andrrizzi I think there is still a TODO in the text to give slightly more detailed example on how to define a weak and strong binder, if you could take a look at this that would be great! You can find the TODO on page 16 of the current draft.

**Comment by andrrizzi** [comment]
I addressed that TODO while working on #80. I think this issue can be closed.
