### ISSUE TITLE
Fig8/Fig9 sampling convergence and forward and backward

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#42]
Do we want both of these figures:
[free_energy_trajectories.pdf](https://github.com/michellab/alchemical-best-practices/files/3932868/free_energy_trajectories.pdf)
[Forward_Reverse_Fig.pdf](https://github.com/michellab/alchemical-best-practices/files/3932870/Forward_Reverse_Fig.pdf)
If so, I need the data for the second one. Or is first figure replacing the second one?

**Comment by mrshirts** [comment]
I think those are two different things.  The second one is convergence
analysis from the Mobley group, looking at the simulation comparing the
free energy using the first and last N samples,  probably from
https://link.springer.com/article/10.1007/s10822-015-9840-9.  I'm not sure
what the first one is, but it's something different.

**Comment by ppxasjsm** [comment]
Ok I thought so. Any chance you still have data for the forward_reverse_fig.pdf somewhere, so we can not just add the pdf?

**Comment by mrshirts** [comment]
The data is for forward_reverse_fig.pdf is @davidlmobley 's , not mine.

**Comment by ppxasjsm** [comment]
Ok, I'll make sure to mention it when assigning bits for review. Mostly just concerned about the size and readability of it as a single column figure.

**Comment by andrrizzi** [comment]
The idea of free_energy_trajectories.pdf is to give an example of a well-behaved and fast to converge free energy trajectory (orange) vs a problematic one (blue). @davidlmobley asked me to put it together a few months ago. I think the two figures are showing different things, but there's no problem in removing free_energy_trajectories.pdf if we're already making this point in another way or we reckon we don't need a figure for this.

**Comment by davidlmobley** [comment]
Those are showing two different things. The less important one is probably the forward/reverse one, but they are different.

**Comment by davidlmobley** [comment]
We currently have both of these in there, so marking as resolved.
