### ISSUE TITLE
Reference management?

### ISSUE THREAD

**Issue by mrshirts** [michellab/alchemical-best-practices#44]
Just checking how are the references being stored and managed?  
 We created https://www.zotero.org/groups/2207075/best_practices_in_free_energy_calculations, but I'm not sure how/if we are using it  I note that Toni is a group member, and added a bunch of them, but none recently, and there are only 5 members (David Mobley, myself, Toni, Julien, Bryce Allen).

Toni, what's the current process for managing references among the group?

**Comment by ppxasjsm** [comment]
It is still a zotero file at the moment for most of them. I'll share it to the group. I just created one that only contains references for this paper and not a massively large one with many duplicates in it. 

Also using google style cite keys, i.e. lastname_year_firstword (not with the underscores)

On that note, which reference is shirts.bennet, I thinky ou put that in there, but I am not sure what it is? I'll give a shout out shortly for help with remaining references I need help with.

**Comment by ppxasjsm** [comment]
I added a collection called alchemical to the group we have. This collections should contain most of the references apart from a select few that are found in manual.bib (but no extra ones). If you want to add more references directly to the manuscript, please add them to the alchemical collection and export it as a better bibtex. Does this make sense?

**Comment by mrshirts** [comment]
Sounds good.  I'll add invites to the group for everyone to the email list you just sent.

**Comment by ppxasjsm** [comment]
In case it is still unclear, if everyone just adds bits to alchemical collection I'll make sure the final version gets exported before submission with all the correct cite keys. Will close the issue, since its mostly been addressed.
