### ISSUE TITLE
compiling document fails with missing figures

### ISSUE THREAD

**Issue by agrossfield** [michellab/alchemical-best-practices#45]
Hi all,

As it stands, trying to build a pdf of the document doesn't work well because the figures are referenced as if you're building from the top level directory and saying 
`pdflatex paper/manuscript`

, but livecoms.cls, the bib file, and the bst file are in paper, as if you were building inside the paper directory.

I worked around this by copying the cls and bst files into the top level directory, but going forward you probably want to fix this. However, the refs don't render in the document, at the moment.

**Comment by ppxasjsm** [comment]
Thanks will make sure to change that!

**Comment by ppxasjsm** [comment]
09fd3416484e11c57ef671e327485df3da50dff0 fixes this issue.
