### ISSUE TITLE
[Sec:3] Theory Needs expansion

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#49]
This section still needs a little expansion. I am happy to work on it, and have an idea of hopefully a relatively easily digestible approach to it, but if people get there before also happy with that. I'll loosely assign myself in any case.

**Comment by andrrizzi** [comment]
Just leaving this comment as a reminder that the standard concentration is also discussed in Section 7 ("Absolute free energy calculations must handle the standard state and use restraints") so that we can avoid unnecessary duplications.

**Comment by ppxasjsm** [comment]
I think they should be slightly different. Once is background theory, the other is, how you would go about addressing the standard state in simulations.

**Comment by ppxasjsm** [comment]
I have made some edits to the section, some feedback/comments would be helpful though.

**Comment by andrrizzi** [comment]
I noticed that in this section we are defining configurational integral and difference in free energy two times using slightly different notations. I can take a pass and try to improve the flow and the coherence of the theory section if that's ok.

**Comment by ppxasjsm** [comment]
That would be wonderful! Thank you!

**Comment by andrrizzi** [comment]
I've expanded the material in section 3 on overleaf. Please feel free to revert/modify any part of it.

I more or less preserved the approach but converted it into a short tutorial introducing the theory with a few more equations and explanations.

I've also made a few changes to section 7.1.2 to remove the unnecessarily redundant material and make the notation uniform.

**Comment by ppxasjsm** [comment]
Is lambda really a vector and not a scalar?

**Comment by mrshirts** [comment]
It can be a vector.  For example, in GROMACS, LJ and vdw are separate components of a vector (restraints and bonded terms are other components)  and the total free energy is computed as:
dG = \int {\vec{dH/dlambda}  dot d\vec{\lambda).  Thus the vector is converted into a scalar integral.

Think of it as an N-dimensional cube, and any pathway connecting (0,0,0,. . ., 0) and (1,1,1,...,1) is a valid thermodynamic integration path yielding the same free energy of turning all of the interactions off and on.

**Comment by ppxasjsm** [comment]
Yeah makes sense. I guess I have only used it as a factor and never thought of it in more detail. Will make sure that we use  it as a vector uniformly everywhere then.
