### ISSUE TITLE
[Sec:4 subsection] reproducibility:

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#50]
There is a subsection in sec:4 on reproducibility that hasn't been filled in. Can @davidlmobley or @jmichel80 or both of you have a look at it? That would be fantastic. It shouldn't be more than a paragraph that is needed.

**Comment by jmichel80** [comment]
wrote a rough paragraph that could do with a bit of polishing

**Comment by ppxasjsm** [comment]
Thank you!

**Comment by davidlmobley** [comment]
This looks good to me, made a few tweaks on Overleaf but marking as resolved.
