### ISSUE TITLE
[Sec:4 Can I afford the calculation?]

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#51]
What are peoples thoughs on some example calculations regarding affordability? While reading the manuscript I definitely agree that it would be super useful to calculate affordability, but I am not really given the tools on how to do it, or where to look for this information. (Maybe this is fairly obvious, but certainly in terms of synthesis I have no idea myself. )

**Comment by davidlmobley** [comment]
I don't think we actually ought to run numbers here. Too much depends on the specifics of people's setups, equipment, etc -- both experimentally and computationally. I'm just trying to tell people that they OUGHT to make some estimate of this themselves.

I added another paragraph to try and explain a little more about what I mean.

To put it another way -- about half the time when experimental collaborators come to me with a project idea, I send them away by telling them, "No, you can measure that better/faster than we can do the calculations and you'll be able to trust the results more." There are applications where free energy calculations make sense -- but not all applications where you COULD do free energy calculations are applications where they make sense.
