### ISSUE TITLE
[Sec4:, sec:5, sec:6] tidy up

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#52]
Section 5 looks at some aspects specific to drug discovery which is nice. It would be good if all of these sections could be reviewed a little and made more concise where possible and improved in structure. I would suggest for people who wrote these sections to do this. 

Furthermore, it would be great if @davidlmobley and @jmichel80 could double check the references I have put in, in these sections and maybe help with pointing out any additional ones needed. This would be massively appreciated. Thanks.

**Comment by davidlmobley** [comment]
I took a quick pass through Section 5, made some fixes, and added some comments. There is more which could be done -- I'd like to work to improve logical flow and paragraphing and reduce use of passive voice -- but I'm out of time til at least next week. (The references I saw looked good so far though.)

I'll have to get back to Sections 4 and 6.

**Comment by ppxasjsm** [comment]
My plan is to try and improve flow and text
consistency over the weekend to get a coherent final draft.

**Comment by ppxasjsm** [comment]
@davidlmobley Could I ask you to take another look at this? I made some minor changes here, but there were other bits that needed more urgent attention.

**Comment by davidlmobley** [comment]
Made it through Section 4. Reading Section 5 again now, trying to get to Section 6.

**Comment by davidlmobley** [comment]
Done with section 5. There are some comments there which need dealing with. 

I will hopefully get through Section 6 tonight or tomorrow.

**Comment by ppxasjsm** [comment]
Thank you. Will deal with them.

**Comment by davidlmobley** [comment]
OK I made it through section 6 @ppxasjsm . Made some improvements, responded to a couple comments/added a couple comments.
