### ISSUE TITLE
[Fig: perturbation network] Review

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#53]
I added an additional figure to the paper today showing two types of perturbation networks with @JenkeScheen help. At the moment it is quite plane looking. Should chemical structures or cycle closures or the like be added for ease of discussion in the analysis section?

[Figure.pdf](https://github.com/michellab/alchemical-best-practices/files/3952969/Figure.pdf)

**Comment by davidlmobley** [comment]
Yes, if it were me I'd put a 2D structure inside each bubble, and probably also build in some cycle closure stuff. 

Might also be worth citing (in the paper) recent work on improved layouts of chemical graphs, e.g.
- https://onlinelibrary.wiley.com/doi/full/10.1002/jcc.26095
- https://pubs.acs.org/doi/abs/10.1021/acs.jcim.9b00528

I heard that Chemical Computing Group was also doing stuff in this space (A-optimal and D-optimal graphs) but I am not offhand finding that with Google Scholar. I think it's bked into CCG's AMBER-TI thing.

**Comment by ppxasjsm** [comment]
I added structures and cycles etc. here 959cd5d0a75b82d714541a121a12b636f2721b4b.

Will add the additional citations.
