### ISSUE TITLE
[sec:The importance of the alchemical pathway]

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#55]
This section needs work. It is rather general, does not explain concepts well, or give good recommendations that are easy to follow. 
@brycestx , @andrrizzi, @Lnaden, @jchodera, and @Huafeng, can you take a look at this? I would quite like a bit more detail on softcore potentials, what do they look like, how do you actually use the lambda to switch between two states. As far as I am aware there are no good recent resouces for this kind of information and I feel a best practices paper would be a good place for this.  The section is also currently lacking citation and I would be happy to have some additional ones, or better suggestions for the ones that currently exist.

**Comment by mrshirts** [comment]
I wrote a lot of text here, let me know if y'all think this is sufficient.

**Comment by ppxasjsm** [comment]
I'll take another look!
