### ISSUE TITLE
[Sec:8] overall review required

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#56]
This section has a lot of nice bits, but also still needs a bit of work. Can you again check consistency and references for this section in general? I'll add a couple issues for subsections as well.

**Comment by davidlmobley** [comment]
@ppxasjsm I made it through Section 8 and made a bunch of edits, improved paragraphing, and also added some comments. Some of these probably need to be answered by whoever wrote it -- was that @brycestx ??

**Comment by mrshirts** [comment]
I did a bunch more edits on the first half of section 8, up through the "are the simulations any good" section.

**Comment by ppxasjsm** [comment]
Wonderful thank you for your help!
