### ISSUE TITLE
[sec:8] Missing good analysis practice

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#59]
This is more of a general questions. We discuss how to analyse the data and check if the simulations make sense quite thoroughly. I feel there should also be a small subsection on best practices of how to show the results. I was thinking something along these lines here: 
 http://practicalcheminformatics.blogspot.com/2019/02/some-thoughts-on-evaluating-predictive.html

And maybe other topics such as, how to compare to experimental results, what should I look at DG , DDG, what kind of errors, what kind of plots make sense. Should this be included, or would you say this kind of discussion is out of scope?

**Comment by mrshirts** [comment]
Seems in scope.  Display of results is not my forte.

**Comment by davidlmobley** [comment]
Agree it seems in scope.

People also often reference Scott Brown's work on the maximum R^2 that can be expected even out of a perfect model given experimental error. This may also be worth mentioning in such a discussion.

**Comment by ppxasjsm** [comment]
There is a small section on this now. I am not sure if we mention Scott Brown's work. I'll double check and add if necessary.

**Comment by ppxasjsm** [comment]
This was added.
