### ISSUE TITLE
How best to add new text?

### ISSUE THREAD

**Issue by mrshirts** [michellab/alchemical-best-practices#60]
Toni, what's the best way to add text over the next 10 days?  Should we do it on Overleaf, or through PR?  Is either mechanism OK?

**Comment by ppxasjsm** [comment]
No idea what the best option is. Either sound good.

**Comment by mrshirts** [comment]
Is there a preferred way so we don't collide?

**Comment by ppxasjsm** [comment]
Feature branch and pull request is probably easiest. Maybe make an announcement what section you are working on in the issue tracker with a -[WIP] and close when done? 

If it’s only small edits track changes in overleaf should be fine I think.
