### ISSUE TITLE
Authorship proposal

### ISSUE THREAD

**Issue by mrshirts** [michellab/alchemical-best-practices#61]
I would propose that Toni get first authorship (or last, whichever is more useful for her at this point) and the rest of us be ordered alphabetically. I think there is a difference in quantity there.  

We can hold off such a decision until it's ready to submit, though.

**Comment by jmichel80** [comment]
Yes Toni's contributions should be recognised

**Comment by davidlmobley** [comment]
I agree, yes.

**Comment by ppxasjsm** [comment]
Thank you for the endorsement. I'll provisionally put me first and will order everyone else alphabetically.
