### ISSUE TITLE
Reference "basic simulation training" rather than giving a list here?

### ISSUE THREAD

**Issue by davidlmobley** [michellab/alchemical-best-practices#62]
We have a prior article in LiveCoMS on "basic simulation training" that intends to provide an overview of the basic fundamentals people should know before even starting, along with giving a list of books/materials people may want to read. I wonder if section 2 ought to simply refer to that rather than trying to provide its own, separate list of texts people should read? It seems redundant to do so.

See eg https://github.com/MobleyLab/basic_simulation_training

@ppxasjsm thoughts?

**Comment by ppxasjsm** [comment]
I agree!

**Comment by ppxasjsm** [comment]
I changed the manuscript to reflect this.
