### ISSUE TITLE
formalize subsection vs subsection*?

### ISSUE THREAD

**Issue by mrshirts** [michellab/alchemical-best-practices#63]
We should decide if we want numbering or not on subsections. I kind of like having numbers, but the most important part is to be consistent.

**Comment by davidlmobley** [comment]
I do like having numbering on subsections, as it makes it much easier to reference them from elsewhere (other sections, or other articles, etc.).

**Comment by ppxasjsm** [comment]
Happy with numbers! Will make sure there are numbers.

**Comment by ppxasjsm** [comment]
Done
