### ISSUE TITLE
Are we taking advantage of previous reviews?

### ISSUE THREAD

**Issue by mrshirts** [michellab/alchemical-best-practices#64]
We should try to make sure we have covered the important points from previous reviews (or reject the points because they are beyond scope or wrong), and also referred to them for certain information that is beyond the scope of what we want to study.  

Particular papers:
"Best Practices in Free Energy Calculations for Drug Design": https://doi.org/10.1007/978-1-61779-465-0_26
"An Introduction to Best Practices in Free Energy Calculations". https://doi.org/10.1007/978-1-62703-017-5_11
"Good Practices in Free-Energy Calculations": http://dx.doi.org/10.1021/jp102971x
"Practical Aspects of Free-Energy Calculations: A Review": https://doi.org/10.1021/ct500161f
"Guidelines for the analysis of free energy calculations", https://link.springer.com/article/10.1007/s10822-015-9840-9

Probably others . . . .

**Comment by ppxasjsm** [comment]
I'll go through this and check with the final checks of the document over the next few days.

**Comment by mrshirts** [comment]
Probably worth dividing up the work.  I am willing to read over the documents that I am a co-author on.  Probably we want people to identify other reviews we should check over as well.

**Comment by ppxasjsm** [comment]
Please post away!

**Comment by brycestx** [comment]
I can cross check with what we did on "Relative Binding Free Energy Calculations in Drug Discovery: Recent Advances and Practical Considerations": https://doi.org/10.1021/acs.jcim.7b00564 in regards to RBFE calculations

**Comment by jmichel80** [comment]
The topics in some subsections in 4.X , 6.X and 7,X have also been touched on in ref 44

**Comment by ppxasjsm** [comment]
which one is reference 44 I have just been messing around with references.

**Comment by jmichel80** [comment]
Prediction of protein-ligand binding affinity by free energy simulations: assumptions, pitfalls and expectations Michel, J. ; Essex, J. W. J. Comput. Aided Mol. Des., 24 (8), 639 -658 2010 http://dx.doi.org/10.1007/s10822-010-9363-3

**Comment by ppxasjsm** [comment]
I tried to take these reviews into consideration, but maybe a few more explicit sentences in the early parts of the document would be helpful.
