### ISSUE TITLE
Figure 9 -- data and legibility

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#68]
Figure 9 currently only has a pdf and not the underlying data and plotting script available. The labels are pretty small and difficult to read. @brycestx I believe you made the figure, can you help out?

**Comment by brycestx** [comment]
Good call, working on this now!

**Comment by brycestx** [comment]
Just updated figure and added raw data in this [commit](https://github.com/michellab/alchemical-best-practices/commit/ad3d379e6ac03288af7179b32800f5616ecb7c2c). @ppxasjsm please review and let me know your thoughts

**Comment by ppxasjsm** [comment]
@brycestx that's great! I made some very minor tweaks to it. Hope that is ok. Just  thought it would be good if the look of the figures is somewhat uniform and didn't think the coloured axes added much. I didn't touch the original code you had, so if you really disagree with my changes we can revert to what you added. I also increased the tick label size. Generally happy with the figure now.

**Comment by brycestx** [comment]
I love it! Thank you!

**Comment by ppxasjsm** [comment]
:)
