### ISSUE TITLE
Question on documents

### ISSUE THREAD

**Issue by mrshirts** [michellab/alchemical-best-practices#7]
There are two documents: 'manuscript.tex' and paper/manuscript.tex. It looks like the one in the main directory is more complete, but doesn't compile because of the lack of the style sheet.  Do I have permission to copy 'manuscript.tex' over to 'paper/manuscript.tex' and delete the redundant file?

**Comment by mrshirts** [comment]
There's also a jdc_edits branch.  This week will be the best time for me in a while to work; so give us a little direction as to which way to go, and I cram in some text and do some cleanup.

**Comment by ppxasjsm** [comment]
Apologies for the delay in reply. I have merged your updates @mrshirts. The default branch should be v1.0 from which to branch.

@jchodera can I merge the stuff from your branch into v1 in terms of abstract and introduction?

**Comment by mrshirts** [comment]
I would go ahead and merge in so we have all the information there.

**Comment by ppxasjsm** [comment]
Going ahead with this.
