### ISSUE TITLE
7.2.4 sampling schemes

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#78]
Up fro review.

**Comment by davidlmobley** [comment]
I wonder if we should be mentioning more general expanded ensemble methods, eg like Brooks' lambda dynamics, etc. It seems somewhat strange to skip lambda dynamics and other expanded ensemble techniques and instead to mention SAMS, where there HAVE been binding free energy studies with expanded ensemble techniques generally but none yet with SAMS. 

Maybe we ought to be adjusting this section so it mentions expanded ensemble generally and gives SAMS only as a special case of it?

**Comment by davidlmobley** [comment]
Taggin @andrrizzi @Lnaden @jchodera and @mrshirts for input here.

**Comment by davidlmobley** [comment]
OK, I took a pass through this and cleaned up the language quite a bit. Except for the issue above I'm marking my part of this as resolved.
