### ISSUE TITLE
7.2.3 alchemical pathway

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#79]
Mostly all there, review would be great!
There are some missing references I am unsure of and some fo the thermodynamic length stuff needs to be clarified.

**Comment by jmichel80** [comment]
Done some minor edits, mostly because I don't think it's 100% true on arbitrary systems that the step wise approach is always better than the direct approach. Tidy up and finalize.

**Comment by Lnaden** [comment]
I've made an editing pass through this section and I think its close to ready now. I stripped out most of the things I could not find citations for or were not true in general, then indicated as such.  There is one block I could not find a citation for, but I found the original writer.

@jmichel80 I think your comment about the step wise approach was correct and restructured that paragraph to reflect it.

@ppxasjsm I added the new citations to the group Zotero, and specifically to the `alchemcal` collection for new ones but was a bit unclear as to how you wanted me to transfer those to the document. Based on  #44 you said you would do a final export at the end, so I have not touched the `alchemical1.bib` file in this repo/overleaf doc itself.

@davidlmobley Do you have the citation for this block which you made in 0a18c6a8fadb6130f0b31eb879a5b053de959c6c? Its this text:

```tex
An example of this approach for relative binding free energy calculations includes saving configurations from short 10 picosecond simulations starting at $\lambda_0$, and evaluating changes in the standard error of mean (SEM) in $\frac{dU}{d\lambda}$ as reevaluated at new values of $\lambda$, starting with a step size of 0.01 up to a predetermined threshold.
This threshold can be empirically defined as the number of atoms being inserted or deleted in the simulation / 100.
If the absolute value of the difference in SEM is below the defined threshold, then the change in $\lambda$ for re-evaluation of SEM in $\frac{dU}{d\lambda}$ is defined by the current difference in SEM from the threshold divided by the derivative of the SEM with respect to $\lambda$.
```

**Comment by davidlmobley** [comment]
@Lnaden -- are you **sure** that is from me? It (a) doesn't sound like me, (b) I don't remember having read it before, much less written it, and (c) can't imagine what a citation for that would be. 

I realize GitHub says it was me. But I suspect what's going on here is that someone else edited Overleaf, and that commit was just me synchronizing Overleaf changes with those here. I suspect it comes from @brycestx , @jmichel80 or @jchodera .

**Comment by Lnaden** [comment]
> are you sure that is from me?

No, I was going based on Github

> I realize GitHub says it was me. But I suspect what's going on here is that someone else edited Overleaf,

Yeah, that makes more sense. I'll look through the Overleaf logs from that time and see if I can be more precise on the author. Thanks!

**Comment by ppxasjsm** [comment]
I’ll update citations as long as they are  in the collection, thanks @Lnaden.

Yeah only @davidlmobley seems to push to fit from overleaf, so it’s not easy to track. I think @mrshirts had a go at this section?

**Comment by Lnaden** [comment]
Found it, @brycestx was the author for that back on Mar 25, 2019. @brycestx any notion to what that was referencing? Otherwise we can just cut it.

**Comment by brycestx** [comment]
@Lnaden Yes that was me. Let's cut it out. It is a scheme that was working well for us internally at STX for larger relative perturbations and we have not published it.

**Comment by Lnaden** [comment]
Awesome, thanks for the update I've cut it and resolved the comment.
