### ISSUE TITLE
Section 2

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/alchemical-best-practices#84]
I incorporated a bunch of suggestions from people here and in general just gives a quick overview of the paper. If people could add to the list of symbols that might be helpful. 

Also list of common terminology Aye or Ney?

**Comment by agrossfield** [comment]
For what it’s worth, a broken out list of common terms, perhaps formatted like a glossary, can be really useful for new students trying to use your paper to get up to speed. We did something like that in the statistical error best practices paper.

Dr. Alan Grossfield
Department of Biochemistry and Biophysics
University of Rochester Medical Center

On Jan 20, 2020, at 4:36 PM, Toni Mey <notifications@github.com> wrote:

﻿

I incorporated a bunch of suggestions from people here and in general just gives a quick overview of the paper. If people could add to the list of symbols that might be helpful.

Also list of common terminology Aye or Ney?

**Comment by ppxasjsm** [comment]
Good to know! So will expand on it. I'll take a look on how you did it.

**Comment by davidlmobley** [comment]
Enthused about list of common terminology. I'll have a quick look at that section and the tables there.

**Comment by davidlmobley** [comment]
OK, took a pass.
