### ISSUE TITLE
Watch paragraphing

### ISSUE THREAD

**Issue by davidlmobley** [michellab/alchemical-best-practices#85]
I've been cleaning it up some as I edit, but in general, paragraphing needs help. It looks like someone has taken out a lot of the (otherwise logical) paragraph breaks and made a lot of subsections into single paragraphs. This should not be and makes for difficult reading.

Subsections should, in my opinion, usually be multiple paragraphs; if it's a single paragraph, I find myself asking, "Why do we need a subsection for that?" 

Also, paragraphs should each have a single main point, usually concisely stated in the first sentence. If a paragraph has multiple main points or it is unclear what the main point is, it usually needs to be broken into multiple paragraphs.

**Comment by ppxasjsm** [comment]
I may have been the culprit of this. Will check what I have done. Thanks for raising it!
