### ISSUE TITLE
constraints, TI, gromacs

### ISSUE THREAD

**Issue by vgapsys** [michellab/alchemical-best-practices#90]
page 16: "At present the most general solution to this problem is simply to avoid the use of constraints (and thus use a smaller timestep if necessary, usually of around 1fs) in any relative free energy calculation involving a transformation of a constrained bond, as done by GROMACS."

dH/dlambda calculated by Gromacs has a contribution from the LINCS constrained bonds, thus transforming constrained bonds is not a problem for TI with Gromacs.

**Comment by ppxasjsm** [comment]
Great thanks! I'll fix this.

**Comment by ppxasjsm** [comment]
commit 02a8c2e fixes this.
